#In this notebook, we're going to cover some of the most fundementals concepts of tensors using tensorflow

More specifically, we're going to cover:
* Intro to tensors
* Getting information from tensors 
* Manipulating tensors
* Tensors & numpy 
*usign @tf.function (a way to speed up your regulat python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercise to try for myself

## Introduction to Tensors

In [2]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__) 

2.6.0


In [3]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the number of dimensions of a vector
vector.ndim

1

In [7]:
#create a matrix
matrix = tf.constant([[10,7],[10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [8]:
# check the number of dimensions of a matrix
matrix.ndim

2

In [9]:
#create a another matrix
another_matrix = tf.constant([[10.,7.],[10.,7.],[8.,9.]], dtype=tf.float16) # specify the data dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [10.,  7.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
 # check the number of dimensions of a matrix
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

what we've created so far:
* Scalar: a single number
* vector: a number with direction
* Matrix: a 2 dimnesional array of numvers
* Tensor: an n-dimensional array of numbers (when n can be any number, 0 for scalar, 1 for vector)

### creating tensor with tf.Variable

In [13]:
# create the same tensor using tf.Variable as above
changeable_tensor = tf.Variable([10,7])  
unchangeable_tensor = tf.constant([10,7])  
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# lets try to change one of the elements in our changeable tensor
#changeable_tensor[0] = 7

In [15]:
# how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# lets try change our unchangeable tensor
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor


### create random tensors


In [17]:
# lets create two random  (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in a tensor

In [18]:
# shuffle a tensor (valueable for when you want to shuffle your data so the inherent order doensn't effevt learning)
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
# shuffle our not_shuffled tensor
#tf.random.shuffle(not_shuffled)
# shuffle our not_shuffled tensor with seed 
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### other ways to make tensors

In [20]:
# Create a tensor of all ones 
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# Create a tensor of all zeros 
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors 

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for computing)
otherwise they are very similar

In [22]:
#you can also trun numPy arrays into tensors
import numpy as np 
numpy_A = np.arange(1,25, dtype=np.int32) # crate a Numpy array bet 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) Non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A,shape=(2,3,4)) # multiply of the dimensions should equal the length of the vector e.g 2*3*4 = 24 
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors 
when dealing with tensors you probably want to be aware of the following attribuites:
* shape
* Rank 
* Axis or dimension
* Size

In [24]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements aling 0 axis:", rank_4_tensor.shape[0])
print("Elements along last axis",rank_4_tensor.shape[-1])
print("Total number of elements in the tensor",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements aling 0 axis: 2
Elements along last axis 5
Total number of elements in the tensor 120


### Tensors can be indexed just like python lists

In [27]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1,:1,:,:1]


<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [29]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [30]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [31]:
# Add in extra dimension to ourrank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ... is means include all the dimensions exists == :,:,:,:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # "-1" means exand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
tf.expand_dims(rank_2_tensor,axis=0) # expan the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipualting tebsors (tensor operations)
**Basic operations**

In [34]:
# you can add values to a tensor uusing the addition operator 
tensor = tf.constant([[10,7],
                      [3,4]])
tensor +10 # same for multiplication and substract

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [35]:
 # We can use the tensorflow built-in function too
 tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In machine learning matrix multiplication is one of the common tensor operations.

In [36]:
# Matrix multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [37]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [38]:
# Create a tensor (3,2) tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# Create a tensor (3,2) tensor
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [39]:
#X @ tf.reshape(Y,shape=(2,3))
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [40]:
#Can do the same with transpose
X,tf.transpose(X), tf.reshape(X,shape=(2,3))


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [41]:
# try matrix multiplication with transpose rather than reshape 
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**
Matrix multiplication is also referred to as the dor product.
You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [42]:
# perform the dot product on X and Y (requres X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [43]:
# Perfomr matrix multiplication between X and Y (trasnposed) 
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [44]:
# Perfomr matrix multiplication between X and Y (reshaped) 
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [45]:
# check the values of Y, and reshape Y and transposed Y
print("Normal Y;")
print(Y,"\n")

print("Y reshaped to (2,3);")
print(tf.reshape(Y,(2,3)),"\n")

print("Y transposed: ")
print(tf.transpose(Y),"\n")

Normal Y;
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3);
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



Generally, when you perform matrix multiplication on 2 tensors and one of the axis doesn't line up, you will transpose rather than reshape one of the tensors to get satisfy  the matrix multiplication rules.

### changing the datatype of a tensor

In [46]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [47]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [48]:
# change from float32 to float16 (reduced percision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [49]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### Aggregating tensors
 Aggregating tensors = condensing them from multiple values down to a smaller amount of values.


In [50]:
# Get the absolute values 
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

lets go through the following forms of aggregation:
* Get the min* Get the max.
* Getthe mean of tensor
* Get the sum of tensor

In [51]:
# Creating a random tesnorwith values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
tf.size(E),E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [52]:
# Find the minimium and max
tf.reduce_min(E)
tf.reduce_max(E)
# Find the mean
tf.reduce_mean(E)
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2619>

In [53]:
# Find the variance of our tensor 
import tensorflow_probability as tfp
tfp.stats.variance(E)
tf.math.reduce_variance(tf.cast(E,tf.float32)) # both ways are right

<tf.Tensor: shape=(), dtype=float32, numpy=867.39557>

In [54]:
# standard deviation
tf.math.reduce_std(tf.cast(E,tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.45158>

### Find the positional maximium and minimium

In [55]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [56]:
# Find the maximum position
max = tf.argmax(F)
max, F[max]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [57]:
# Find the minimum position
min = tf.argmin(F)
min, F[min]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [58]:
assert tf.reduce_min(F) == F[min] # using assert to throw eror if they are not equal otherwise no output

### Squeezing a tensor (removing all single dimensions)

In [59]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [60]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [61]:
G_squeezed = tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tenors

In [62]:
# Create a list of indicies
some_list = [0,1,2,3] # could be red, green, blue, purple
depth = 4
tf.one_hot(some_list,depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [63]:
# Specify custon values for one hot encoding 
tf.one_hot(some_list,depth,on_value="ooooh",off_value="Nooooo")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ooooh', b'Nooooo', b'Nooooo', b'Nooooo'],
       [b'Nooooo', b'ooooh', b'Nooooo', b'Nooooo'],
       [b'Nooooo', b'Nooooo', b'ooooh', b'Nooooo'],
       [b'Nooooo', b'Nooooo', b'Nooooo', b'ooooh']], dtype=object)>

### Squaring, logm square root

In [64]:
# Create a new tensor 
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [65]:
# Square it 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [66]:
# Find the square root (method required non int values)
tf.sqrt(tf.cast(H,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [67]:
tf.math.log(tf.cast(H,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor and NumPy

TensorFlow interacts beautifully with Numpy 





In [68]:
# Create a tensor directly from a NumPy array 
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [69]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [70]:
# Convert tensor J to a NumPy array
J.numpy()

array([ 3.,  7., 10.])

In [71]:
J = tf.constant(np.array([3.]))
J

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([3.])>

In [73]:
# the defaulr types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# check he data types of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)